#!/bin/bash

# $Id$
#*********************************************************************
#
# get-config-dir-http -- get a tarball of the config dir
#
# This script is part of FAI (Fully Automatic Installation)
# Copyright (C) 2000-2010 Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#*********************************************************************

### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:  $FAI_CONFIG_SRC $FAI
# Suggests-Var:
# Short-Description: get config space via http
### END SUBROUTINE INFO

fdir=/var/lib/fai

cd $fdir

# determine basename of tar file to download (later used as class name)
file=${FAI_CONFIG_SRC##*/}
base=${file%%.*}

# get md5sum first
if wget -q -t5 -O $fdir/$file.md5 ${FAI_CONFIG_SRC}.md5; then
   echo "Checksum file $file.md5 successfully downloaded."
else
   ret=$?
   echo "Checksum file ${FAI_CONFIG_SRC}.md5 failed to download. Aborting." >&2
   exitcode_error_getconfig $ret 885 "${FAI_CONFIG_SRC}.md5"
fi

# now download tarball of config space
echo -n "Getting configuration space tarball from $FAI_CONFIG_SRC ..."
if wget -q -t 3 $FAI_CONFIG_SRC; then
    echo "done"
else
    exitcode_error_getconfig $? 886 "$FAI_CONFIG_SRC"
fi

# check the md5 sum
echo -n "MD5 checksum of "
if ! md5sum -c $file.md5; then
    exitcode_error_getconfig $? 887
fi

# extraxt the downloaded file using ftar. Therefore define a class
# with the basename of the file
echo "Extracting config space from $file"
ftar -c $base -t $FAI -s $fdir .
exitcode_error_getconfig $? 888
